spring:
  profiles:
    active: local
    include:
      - domain
      - external
      - oauth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 544385537574-774c31vj941hkdl0fp70vt0skjc3je3n.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: c72139d8987d18a01da876852d181267
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

token:
  expiration_time: 86400000
  secret: secret


