spring:
  profiles:
    active: local
    include:
      - domain
      - external
      - oauth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 544385537574-774c31vj941hkdl0fp70vt0skjc3je3n.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1129306567796641
            client-secret: 906862fcf400aec6f0e4b28452eb0be6
            scope:
              - email
              - public_profile
          kakao:
            client-id: c72139d8987d18a01da876852d181267
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
          naver:
            client-id: KJPFs_Lf5t3L81JjcKWR
            client-secret: mbaBXEF8TR
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  mail:
    host: smtp.naver.com
    port: 465 # 네이버 이메일 포트
    username: wolfmob@naver.com
    password: asfos9612!
    # 전송 위한 prop, ssl의 신뢰 및 권한 등 사용허가
    properties:
      mail.smtp.auth: true
      mail.smtp.enable: true
      mail.smtp.ssl.trust: smtp.naver.com


token:
  expiration_time: 86400000
  secret: secret


