version: "3.7"

services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./usr/src/app/build:/usr/share/nginx/html

    
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client/:/usr/src/app"
      - "/usr/src/app/node_modules"
    networks:
      - frontend

networks: 
  frontend:
    driver: bridge