spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i7b306.p.ssafy.io:3306/drinkus?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      #update -> 삭제안하고싶을때 #none -> 배포시에(운영환경)
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: false
        format_sql: true
    open-in-view: false
#    generate-ddl: true

logging:
  level:
    org.hibernate.SQL: debug
#spring:
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#
#  jpa:
#    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        default_batch_fetch_size: 500
#        #        show_sql: false
#        format_sql: true
#    open-in-view: false
#
#logging:
#  level:
#    org.hibernate.SQL: debug